bind = "0.0.0.0:25577"
player-info-forwarding-mode = "modern"
forwarding-secret-file = "${FORWARDING_SECRET_FILE}"

[servers]
survivencia = "mc-sobrevivencia:25565"
lobby = "mc-sobrevivencia:25565"
minigames = "mc-sobrevivencia:25565"
factions = "mc-sobrevivencia:25565"

try = ["survivencia"]

[forced-hosts]
"minigames.example.com" = ["minigames"]
"lobby.example.com" = ["lobby"]
"factions.example.com" = ["factions"]
